[package]
name = "rhack"
version = "0.1.0"
authors = ["nakabonne <ryo@nakao.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
home = "0.5.3"