[package]
name = "rhack"
version = "0.1.0"
authors = ["nakabonne <ryo@nakao.dev>"]
edition = "2018"
license-file = "LICENSE"
description = "Temporary edits to your Rust dependencies"
readme = "README.md"
homepage = "https://github.com/nakabonne/rhack"
repository = "https://github.com/nakabonne/rhack"
keywords = ["cli", "cargo", "dependency", "crate"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
home = "0.5.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml_edit = "0.2.0"
